version: 0.2
phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR.."
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 992382573619.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t my-flask-app .
      - docker tag my-flask-app:latest 992382573619.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest 
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 992382573619.dkr.ecr.us-east-1.amazonaws.com/my-flask-app:latest
artifacts:
    files:
        - imagedefinitions.json

